// Generated by IB v0.4.1 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate
@end

@implementation LoginViewController
@end

@implementation ProfileViewController
@end

@implementation ProjectsTableViewController
@end

@implementation RecentTableViewController
@end

@implementation Build
@end

@implementation Circle
@end

@implementation Me
@end

@implementation Project
@end

@implementation BuildViewCell
@end

@implementation ProjectViewCell
@end

