// Generated by IB v0.4.1 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>
#import <UIKit/UIKit.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
@end

@interface LoginViewController: UIViewController

@property IBOutlet id input_field;
@property IBOutlet UIButton * sign_in_btn;

-(IBAction) viewDidLoad;
-(IBAction) viewDidUnload;
-(IBAction) shouldAutorotateToInterfaceOrientation:(id) interfaceOrientation;
-(IBAction) sign_in:(id) sender;
-(IBAction) alert_error;
-(IBAction) textFieldShouldReturn:(id) text_field;
-(IBAction) textFieldFinished:(id) sender;

@end

@interface ProfileViewController: UIViewController

@property IBOutlet id profile_image_view;
@property IBOutlet id email_label;
@property IBOutlet id token_label;

-(IBAction) viewDidLoad;
-(IBAction) viewDidUnload;
-(IBAction) shouldAutorotateToInterfaceOrientation:(id) interfaceOrientation;
-(IBAction) gravatar:(id) email;

@end

@interface ProjectsTableViewController: UITableViewController
-(IBAction) viewDidLoad;
-(IBAction) viewDidUnload;
-(IBAction) load_projects;
-(IBAction) shouldAutorotateToInterfaceOrientation:(id) interfaceOrientation;
-(IBAction) numberOfSectionsInTableView:(id) tableView;
-(IBAction) refresh;

@end

@interface RecentTableViewController: UITableViewController
-(IBAction) viewDidLoad;
-(IBAction) viewDidUnload;
-(IBAction) load_recent_builds;
-(IBAction) viewDidAppear:(id) animated;
-(IBAction) shouldAutorotateToInterfaceOrientation:(id) interfaceOrientation;
-(IBAction) numberOfSectionsInTableView:(id) tableView;
-(IBAction) refresh;

@end

@interface Build: NSObject
-(IBAction) initialize:(id) attrs;
-(IBAction) username;
-(IBAction) gravatar:(id) size;
-(IBAction) status_color;
-(IBAction) repo_name;

@end

@interface Circle: NSObject
-(IBAction) initialize;
-(IBAction) default_headers;

@end

@interface Me: NSObject
-(IBAction) initialize:(id) attrs;

@end

@interface Project: NSObject
-(IBAction) initialize:(id) attrs;
-(IBAction) all_branches;
-(IBAction) branch_name;
-(IBAction) repo_name;

@end

@interface BuildViewCell: UITableViewCell

@property IBOutlet id build_label;
@property IBOutlet id status_view;
@property IBOutlet id subject_label;
@property IBOutlet id committer_label;
@property IBOutlet id avatar_view;

@end

@interface ProjectViewCell: UITableViewCell

@property IBOutlet id name_label;
@property IBOutlet id branch_label;
@property IBOutlet id build1_view;
@property IBOutlet id build2_view;
@property IBOutlet id build3_view;
@property IBOutlet id build4_view;
@property IBOutlet id build5_view;

-(IBAction) setup_build_views:(id) project;

@end

